name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1

  build:
    runs-on: ${{ matrix.build-on }}
    needs: create-release
    strategy:
      matrix:
        include:
          - cpu: x86_64
            os: linux
            target: x86_64-unknown-linux-musl
            build-on: ubuntu-latest
            use-cross: false
            install-musl: true
            exe: ""
            run-tests: true
          - cpu: aarch64
            os: linux
            target: aarch64-unknown-linux-musl
            build-on: ubuntu-latest
            use-cross: true
            install-musl: false
            exe: ""
            run-tests: false
          - cpu: aarch64
            os: macOS
            target: aarch64-apple-darwin
            build-on: macos-latest
            use-cross: true
            install-musl: false
            exe: ""
            run-tests: false
          - cpu: x86_64
            os: macOS
            target: x86_64-apple-darwin
            build-on: macos-latest
            use-cross: false
            install-musl: false
            exe: ""
            run-tests: true

    name: Build Release ${{ matrix.cpu }} ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Rust and add toolchain ${{ matrix.target }}
        if: ${{ !matrix.use-cross }}
        run: |
          rustup update 
          rustup target add ${{ matrix.target }}

      - name: Install bin install if needed
        if: ${{ matrix.use-cross }}
        run: |
          wget -qO- https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz | tar xvz -C ~/.cargo/bin

      - name: Install cross if needed
        if: ${{ matrix.use-cross }}
        run: |
          cargo binstall cross -y

      - name: Run tests
        if: ${{ matrix.run-tests }}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --profile release-lto --target ${{ matrix.target }} -- --nocapture

      - name: Build binary target/${{ matrix.target }}/release/yaftp
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use-cross }}
          command: build
          args: --bin gftp --features=bin --profile release-lto --target ${{ matrix.target }}

      - name: Gz asset
        run: |
          set -ex
          mv target/${{ matrix.target }}/release-lto/gftp${{ matrix.exe }} target/${{ matrix.target }}/release-lto/yaftp${{ matrix.exe }}
          tar -cf - -C target/${{ matrix.target }}/release-lto/ yaftp${{ matrix.exe }} | gzip -9 > yaftp.tar.gz
          tar -cf - -C target/${{ matrix.target }}/release-lto/ yaftp${{ matrix.exe }} | xz -9 > yaftp.tar.xz

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: yaftp${{ matrix.exe }}.tar.gz
          asset_name: yaftp-${{ matrix.os }}-${{ matrix.cpu }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: "Gzipped binary for ${{ matrix.cpu }} ${{ matrix.os }}"

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: yaftp${{ matrix.exe }}.tar.xz
          asset_name: yaftp-${{ matrix.os }}-${{ matrix.cpu }}.tar.xz
          tag: ${{ github.ref }}
          overwrite: true
          body: "Xzipped binary for ${{ matrix.cpu }} ${{ matrix.os }}"

      - name: Upload config
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: conf/yaftp.json
          asset_name: yaftp.json
          tag: ${{ github.ref }}
          overwrite: true
          body: "Configuration file for yaftp"
